### ISSUE TITLE
HybridKit (Portable) not compilable

### ISSUE THREAD

**Issue by RoDo777** [chkn/HybridKit#1]
Maybe I'm doing something completely wrong, but if I try to compile the basic project "HybridKit (Portable)" I get a lot of errors. I only cloned the sources an loaded the missing nuget packages (not even an update to Xamarin Forms), but get compile time errors:

on Line 14 in BundleWebViewSource.cs
static readonly MethodInfo iOS_GetBundleUrl =
            Type.GetType ("HybridKit.BundleCache, HybridKit.iOS")?.GetTypeInfo ().GetDeclaredMethod ("GetBundleUrl");

Do I have to compile it in a specific order or configuration? e.g do I need to compile it while connected with an Xamarin.Host running on a Mac?
# 

Error   15  Invalid expression term '.' C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  15  58  HybridKit
Error   16  Syntax error, ':' expected  C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  15  59  HybridKit
Error   17  ; expected  C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  15  73  HybridKit
Error   18  Method must have a return type  C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  15  74  HybridKit
Error   19  Type expected   C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  15  93  HybridKit
Error   20  Invalid expression term '.' C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  34  27  HybridKit
Error   21  ) expected  C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  34  28  HybridKit
Error   22  Syntax error, ':' expected  C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  34  28  HybridKit
Error   23  Invalid expression term '.' C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  34  70  HybridKit
Error   24  Syntax error, ':' expected  C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  34  71  HybridKit
Error   25  Invalid expression term ',' C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  34  82  HybridKit
Error   26  ; expected  C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  34  82  HybridKit
Error   27  ; expected  C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  34  83  HybridKit
Error   28  Invalid expression term ',' C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  35  54  HybridKit
Error   29  ; expected  C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  35  54  HybridKit
Error   30  ; expected  C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  35  55  HybridKit
Error   31  ; expected  C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  36  19  HybridKit
Error   32  Invalid expression term ')' C:_DEV\Xamarin_PlugIns\chkn\HybridKit\HybridKit\Forms\BundleWebViewSource.cs  37  4   HybridKit

**Comment by chkn** [comment]
Ah it looks like your compiler is choking on some C# 6 features. I'm building with Mono 3.12 on a Mac, and mcs already supports these features. Can you try to compile with Roslyn or Mono?

I'm working on some more documentation-- I'll be sure to add a note about this.

**Comment by RoDo777** [comment]
Thanks for the info. I'll try and give you feedback. May take a while.

**Comment by chkn** [comment]
This has been quiet for awhile and Roslyn/VS 2015 is pretty ubiquitous now, so I'm closing this.
